/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * gui package contains GUI.
 */
package gui;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;

import core.Methods;

import json.ConverterToXML;
import xml.ConverterToJSON;

/**
 * . GUI
 * 
 * @author Groupe 12
 * @version 1.0
 */
public class ConverterFile extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private String input, output, path;
	private ConverterToXML converterToXML = new ConverterToXML();
	private ConverterToJSON converterToJSON = new ConverterToJSON();

	/**
	 * Creates new form ConverterFile
	 */
	public ConverterFile() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		fileChooser = new javax.swing.JFileChooser();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		Open = new javax.swing.JMenuItem();
		Exit = new javax.swing.JMenuItem();

		fileChooser.setDialogTitle("Select a file");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Converter XML - JSON");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jLabel1.setText("XML");

		jLabel2.setText("JSON");

		jMenu1.setText("File");

		Open.setText("Open file");
		Open.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OpenActionPerformed(evt);
			}
		});
		jMenu1.add(Open);

		Exit.setText("Exit");
		Exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitActionPerformed(evt);
			}
		});
		jMenu1.add(Exit);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														368,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										14, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														380,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(20, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														442, Short.MAX_VALUE)
												.addComponent(jScrollPane1))
								.addContainerGap()));

		pack();
	}

	/**
	 * . Action performed onclick open button
	 * @param evt
	 *            ActionEvent
	 */
	private void OpenActionPerformed(
			final java.awt.event.ActionEvent evt) {

		int returnVal = fileChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			// Init TextArea to ""
			jTextArea1.setText("");
			jTextArea2.setText("");
			// Catch the current file path
			path = fileChooser.getSelectedFile().toString();
			path = path.replace("\\", "/");
			File file = fileChooser.getSelectedFile();
			try {
				input = Methods.getFileAsString(path);

			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if (file.getAbsolutePath().endsWith(".xml")) {
				jTextArea1.setText(input);
				try {
					output = converterToJSON.convertToJSON(
							path, false);
					jTextArea2.setText(output);
				} catch (FileNotFoundException e) {
					e.printStackTrace();
				}
			} else if (file.getAbsolutePath().endsWith(".json")) {
				jTextArea2.setText(input);
				try {
					output = converterToXML.convertToXML(
							path, false);
					jTextArea1.setText(output);
				} catch (FileNotFoundException e) {
					e.printStackTrace();
				}
			} else {
				jTextArea1.setText("Select a XML file");
				jTextArea2.setText("Select a JSON file");
			}
		} else {
			System.out.println("File access cancelled by user.");
		}
	}
	/**
	 * . Action performed onclick close button
	 * @param evt
	 *            ActionEvent
	 */
	private void ExitActionPerformed(
			final java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConverterFile.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConverterFile.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConverterFile.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					ConverterFile.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConverterFile().setVisible(true);
			}
		});
	}

	// Variables declaration
	private javax.swing.JMenuItem Exit;
	private javax.swing.JMenuItem Open;
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	// End of variables declaration
}
